version: "3"
services:
  catalog-service-1:
    image: catalog-service
    container_name: catalog-service-1
    build:
      context: ./catalog-service  
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./catalog-service/catalog.csv:/app/catalog.csv  
    networks:
      - network1

  order-service-1:
    image: order-service
    container_name: order-service-1
    build:
      context: ./order-service  
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - network1
    depends_on:
      - catalog-service-1
  

  frontend-service:
    image: frontend-service
    container_name: frontend-service
    build:
      context: ./Frontend
    networks:
      - network1
    depends_on:
      - order-service-1
      
      - catalog-service-1

    stdin_open: true
    tty: true

networks:
  network1:
    driver: bridge
